### ISSUE TITLE
Unable to start application

### ISSUE THREAD

**Issue by ethanzh** [michael-danello/iMessageWrappedRelease#2]
Hello, I am getting the following error
```
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
[nltk_data]     failed: unable to get local issuer certificate
[nltk_data]     (_ssl.c:1108)>
 * Serving Flask app "imessage2020wrapped.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2021-01-01 22:52:06,498] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2447, in wsgi_app
  File "flask/app.py", line 1952, in full_dispatch_request
  File "flask/app.py", line 1821, in handle_user_exception
  File "flask/_compat.py", line 39, in reraise
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "imessage2020wrapped/app.py", line 355, in index
  File "imessage2020wrapped/app.py", line 68, in get_db
sqlite3.OperationalError: unable to open database file
127.0.0.1 - - [01/Jan/2021 22:52:06] "GET / HTTP/1.1" 500 -
[2021-01-01 22:52:08,062] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2447, in wsgi_app
  File "flask/app.py", line 1952, in full_dispatch_request
  File "flask/app.py", line 1821, in handle_user_exception
  File "flask/_compat.py", line 39, in reraise
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1936, in dispatch_request
  File "imessage2020wrapped/app.py", line 355, in index
  File "imessage2020wrapped/app.py", line 68, in get_db
sqlite3.OperationalError: unable to open database file
127.0.0.1 - - [01/Jan/2021 22:52:08] "GET / HTTP/1.1" 500
```

There are also several other users reporting similar errors on [Hacker News](https://news.ycombinator.com/item?id=25603916).

I am running the program with `sudo ./iMessageWrapped`

**Comment by bberenberg** [comment]
I have the same experience as well

**Comment by habi** [comment]
I'm getting the exact same error, on macOS Big Sur, Version 11.1 (20C69).
A Safari window opens, but only shows an "Internal Server Error" win which "The server encountered an internal error and was unable to complete your request."
